import React from "react";
import Home from "../Home";
import "./Legal.css";

function BlockedContentPolicy({ sidebarOpen }) {
  return (
    <Home sidebarOpen={sidebarOpen}>
      <div className="legal-content">

        <h1 className="legal-title">Blocked Content Policy</h1>

        <p className="legal-date">
          <strong>Date of Revision:</strong> August 01, 2025
        </p>

        <p>
          At EverAI Limited, we are committed to providing a secure, respectful,
          and lawful online environment for all users. Certain categories of content
          are strictly forbidden while using Candy.ai and/or any of our platforms,
          products or services (“Services”).
          The Services generally consist of private chats with AI Companions and AI
          images visible to and accessible by individual users.
          Although users cannot upload or share content on the Services,
          the content outlined in this Blocked Content Policy is nevertheless
          prohibited and subject to our moderation controls and reporting policies.
        </p>

        <h2>1. Prohibited Content</h2>

        <p>
          The following content, included but not limited to text, images,
          videos, and any other AI-generated content created on our platform,
          is prohibited:
        </p>

        <p>
          <strong>(a) Illegal Content:</strong> Content that contravenes local,
          national, or international laws and regulations is strictly prohibited.
          This includes, but is not limited to, content associated with illegal
          drugs, weapons, violence, or activities that advocate or endorse illegal actions.
        </p>

        <p>
          <strong>(b) Hate Speech and Discrimination:</strong> We do not tolerate
          content that promotes hate speech, discrimination, or harassment based
          on race, ethnicity, nationality, religion, gender, sexual orientation,
          disability, or any other protected characteristic.
        </p>

        <p>
          <strong>(c) Violence and Harm:</strong> Content that encourages,
          glorifies, or promotes violence, self-harm, or harm to others is strictly prohibited.
          This includes content that endorses suicide, terrorism, or any form of harm.
        </p>

        <p>
          <strong>(d) Child Exploitation:</strong> We have a zero-tolerance policy
          toward child sexual abuse material (CSAM) and any content that exploits
          or endangers minors, including but not limited to CSAM, sexual exploitation,
          or any form of harm or harassment towards minors.
        </p>

        <p>
          <strong>(e) Content Resembling Minors:</strong> It is strictly prohibited
          trying to generate AI content resembling minors. We are committed to ensuring
          that AI-generated content on our platform does not bear any resemblance to minors
          or exploit their likeness.
        </p>

        <p>
          <strong>(f) Infringement on Privacy and Copyright:</strong> Any content that
          infringes upon the privacy, copyrights, trademarks, or intellectual property
          rights of individuals or entities is not permitted. This includes sharing
          personal information without consent, pirated content, or any unauthorized
          use of copyrighted material.
        </p>

        <p>
          <strong>(g) Impersonation and Celebrity Content:</strong> Deceptive or harmful
          impersonation of real individuals, public figures, or celebrities is prohibited.
          This encompasses any misleading attempts to impersonate or misrepresent others.
        </p>

        <p>
          <strong>(h) Non-Consensual Intimate Imagery and Deepfakes:</strong> We have
          a zero-tolerance policy for the creation or attempted creation of non-consensual
          intimate imagery and images intended to resemble actual persons (“deepfakes”).
          This content will be removed and appropriate action taken against anyone
          found violating this policy.
        </p>

        <h2>2. Content Responsibility</h2>

        <p>
          You, as a user of the Services, are solely responsible for the output
          generated by the AI Companions through your input, including any text messages,
          voice messages, images, and videos.
          You understand and agree that EverAI Limited does not control or endorse
          the content generated by the AI Companions, and that you are fully responsible
          for any output generated by the AI and for your own actions while using the Services.
        </p>

        <p>
          You must ensure that your interactions with the AI Companions comply with
          applicable laws, regulations, our other Terms and Policies,
          and you shall not engage in any illegal, unethical, or harmful activities
          while using the Services.
        </p>

        <h2>3. Content Moderation</h2>

        <p>
          While conversations between users and AI Companions are generally confidential,
          we have implemented content moderation controls based on our proprietary
          LLM technology to ensure compliance with our Policies.
          If our moderation controls detect any content that violates our terms,
          we may manually review the flagged content and/or other content associated
          with the account and take appropriate action.
          This may include removing content, terminating the user's account,
          or reporting the content to appropriate authorities.
        </p>

        <h2>4. Prohibited Content Reporting</h2>

        <p>
          We have a zero-tolerance policy for Child Sexual Abuse Material (CSAM).
          Attempting to create CSAM is prohibited by law and our Policies.
          In addition to our other content moderation and removal controls,
          we report known CSAM to the appropriate authorities as required.
        </p>

        <h2>5. Contact Information</h2>

        <p>
          If you believe there has been a violation of this Blocked Content Policy
          or any of our Policies, or you have any questions or require further
          clarification, please contact us at:
          <strong> support@candymail.ai</strong>
          or via the “Contact Us” area in the Services.
        </p>

        <h2>6. Termination</h2>

        <p>
          We have the right to suspend or terminate the use of the Services
          by anyone suspected of violating this or any of our Policies.
        </p>

      </div>
    </Home>
  );
}

export default BlockedContentPolicy;
