import React from "react";
import Home from "../Home";
import "./Legal.css";

function UnderagePolicy({ sidebarOpen }) {
    return (
        <Home sidebarOpen={sidebarOpen}>
            <div className="legal-content">

                <h1 className="legal-title">Underage Policy</h1>

                <p className="legal-date">
                    <strong>Date of Revision:</strong> February 14, 2025
                </p>

                <p>
                    At EverAI Limited we are committed to making sure that Candy.ai and/or any of our online channels, platforms, products or services, including all content contained therein (“Services”) are used in a responsible and safe way by users who meet the legal age requirements.
                </p>
                <p>
                    We are also committed to ensuring that AI-generated content on our Services does not bear any resemblance to minors or exploit their likeness. For this purpose, we have implemented proprietary content moderation controls to ensure full compliance with applicable laws and our own Terms of Service and Terms and Policies (together, “Policies”).
                </p>

                <h2>1. Website Access and Registration</h2>
                <p>
                    We have implemented extensive measures to prevent the registration of underaged users. If you believe your child has improperly accessed the Services, please contact us using the contact information below, so that we can block further access.
                </p>
                <p>
                    When entering the website, users encounter an age gate designed to restrict entry to individuals who are not of legal age is presented to the user. Users must affirm that they are above 18, and this information is used to verify their eligibility to access the website.
                </p>
                <p>
                    A transparent disclaimer emphasizes that users must be 18 years or older to access our services. Users are also notified that providing inaccurate information about their age constitutes a violation of our Terms of Service.
                </p>
                <p>
                    We may also implement further measures to verify that users are adults, in accordance with local requirements.
                </p>
                <p>
                    EverAI Limited cannot be held responsible for any inaccuracies or misrepresentations regarding user age. It is the user’s responsibility to ensure compliance with their local laws and regulations regarding the access and consumption of adult content.
                </p>

                <h2>2. Content Removal Process</h2>
                <p>
                    You, as a user of the Services, are solely responsible for the output generated by the AI Companions through your input, including any text messages, voice messages, images, and videos. The AI Companions respond based on the conversations you lead and the settings you select. You understand and agree that EverAI Limited does not control or endorse any content generated by the AI Companions, and that you are fully responsible for any output generated by the AI and for your own actions while using the Services.
                </p>
                <p>
                    You must ensure that your interactions with the AI Companions comply with applicable laws, regulations, our Policies, in particular the Community Guidelines and Blocked Content Policy and you shall not engage in any illegal, unethical, or harmful activities while using the Services. We emphasize in particular the provisions of these policies prohibiting any content that exploits or poses a danger to minors, including but not limited to child pornography, sexual exploitation, or any form of harm or harassment towards minors as well as any attempt to generate AI content which would bear any resemblance to minors or exploit their likeness.
                </p>

                <h2>3. Content Moderation and Removal</h2>
                <p>
                    We value the safety, respect and integrity of all our users. While conversations between users and AI Companions are generally confidential, we have implemented content moderation controls based on our proprietary LLM technology to ensure compliance with our Policies, in particular with our Community Guidelines.
                </p>
                <p>
                    In the event the moderation controls detect anything that violates any of our Policies, we may manually review the flagged content and/or other content associated with the account and take appropriate action. This may include removing content, terminating the user’s account, or reporting the content to appropriate authorities. See also Section 4 below.
                </p>
                <p>
                    These measures are implemented to maintain a respectful and secure environment for all users. We strive to strike a balance between privacy and community standards, and we appreciate your understanding and cooperation in adhering to our guidelines.
                </p>

                <h2>4. Prohibited Content Reporting</h2>
                <p>
                    We have a zero-tolerance policy for Child Sexual Abuse Material (CSAM). Attempting to create CSAM is prohibited by law and our Community Guidelines and Blocked Content Policy. In addition to our other content moderation and removal controls, we report known CSAM to the National Center for Missing and Exploited Children, or other local authorities as appropriate.
                </p>

                <h2>5. Contact Information</h2>
                <p>
                    If you believe there has been a violation of our Policies – including if you believe your child has improperly accessed the Services – or you have any questions or require further clarification regarding our Underage Policy, please contact us at: support@candymail.ai or via the “Contact Us” area in the Services.
                </p>

                <h2>6. Termination</h2>
                <p>
                    We have the right to suspend or terminate the use of the Services by anyone engaged in suspected violations of any of our Policies.
                </p>

            </div>
        </Home>
    );
}

export default UnderagePolicy;
